services:
  - type: web
    name: cognition-scraper
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres:JhF4FwrVVXu8m9SB@db.pcsudvflktvoyljpajph.supabase.co:5432/postgres
      - key: ADMIN_PWD
        value: cognition2026
